import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";
import { Menu } from "@/components/menu/Menu";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <Menu/>
      {children}
      <Footer/>
      </body>
    
    </html>
  );
}
